---
- name: disable selinux
  selinux:
    state: disabled

- name: install rsync package
  yum:
    name: rsync
    state: latest

- name: create rsyncd.conf
  template: 
    src: rsyncd.conf.j2
    dest: /etc/rsyncd.conf

- name: enable firewall ports
  firewalld: port=873/tcp permanent=true state=enabled
  when: false

- name: restart firewalld service
  service: 
    name: firewalld
    enabled: yes
    state: restarted
  when: false

- name: start rsync daemon
  service: 
    name: rsyncd
    enabled: yes
    state: started
